name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./Parky/Parky.sln

    - name: Build
      run: dotnet build ./Parky/Parky.sln --no-restore -c Release

    - name: Test
      run: dotnet test ./Parky/Parky.sln --no-build -c Release
